import type { Metadata } from "next";
import { recMonoCasual } from "./fonts/fonts";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";
import ModeToggleButton from "@/components/ModeToggle";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${recMonoCasual.className} antialiased bg-page p-24`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<div className="relative w-full h-full">
						<ModeToggleButton />
					</div>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
